name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Deploy to gh-pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: npm install && npm run build
          build_command: npm run build-storybook
          path: storybook-static
          checkout: false
