name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
        name: Cloning repository
      - uses: actions/checkout@v4

      - name: Setup NodeJS (using .node-version)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install dependencies
        run: npm install

      - name: Running linter
        run: npm run lint
