name: Main workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      - name: Run linter
        run: npm run lint

      - name: Run build
        run: npm run build
