name: Release workflow

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: {}

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install && npm run build

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'CHANGELOG.md'
          create-summary: true
          skip-ci: false

      - name: Create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Publish on NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          GITHUB_TOKEN: ${{ secrets.github_token }}
